var pages=null;
(function(){function g(){h&&(document.body.innerHTML='<div>Please use one of the following browsers<ul><li><a href="http://www.google.com/chrome/">Google Chrome</a></li><li><a href="http://www.mozilla.com">Mozilla Firefox</a></li></ul></div>')}var h=!1,f=!1,c=!1,k=function(){if(f&&h)try{var j=document.createElement("Div");document.body.appendChild(j);j.appendChild(CreateBanner(data.about.name,data.about.title));var k=location.pathname.split("/"),k=0==k[1].length?"home":k[1],n={home:{text:"Home",pageFunc:CreateHomePage},
music:{text:"Music",pageFunc:CreateMusicPage},soft:{text:"Software",pageFunc:CreateSoftPage},resume:{text:"Resumes / CVs",pageFunc:CreateResumesPage}},i;for(i in n)window.history&&window.history.pushState&&i!=k?window.setTimeout(function(a){return function(){n[a].page=n[a].pageFunc()}}(i),0):i==k&&(n[i].page=n[i].pageFunc());pages=CreatePageHandler(j,n,"home")}catch(b){console&&(console.log(b.message),console.log(b.stack)),c=!0,g()}};(function(){try{var h=new XMLHttpRequest;h.open("GET","/data.json",
!0);h.addEventListener("readystatechange",function(c){4===c.target.readyState&&200===c.target.status&&(data=JSON.parse(c.target.responseText),f=!0,k())},!1);h.send()}catch(m){c=!0,g()}})();window.addEventListener("load",function(){h=!0;c?g():k()},!1)})();var CreatePageHandler=function(g,h,f){function c(a,d,b){var c="/"+a;d&&0<d.length&&(c+="/"+d.join("/"));if(history[b])history[b]({id:a,subPages:d},escape(a),escape(c))}function k(a,d){c(a,d,"replaceState")}var j=location.pathname.split("/");j.shift();var m=j.shift();""!==m&&(f=m);var n=null,i=document.createElement("Div");i.className="Main";g.appendChild(i);var b=CreateHeader(h,function(a,d){var b=h[a].page;n?transition.fade(i,b.node,function(a){a==transition.SUCCESS&&(n=b);d&&d(a)}):(i.appendChild(b.node),
n=b,d(transition.STARTING),k(a,b.subPages))},f,j),f=CreateAudioPlayer();g.insertBefore(b.node,i);g.appendChild(f.getNode());window.addEventListener("popstate",function(a){(a=a.state)&&a.id&&b.select(a.id,a.subPages,!0);return!0},!1);return obj={gotoPage:function(a,d){b.select(a,d)},pushState:function(a,b){c(a,b,"pushState")},replaceState:k,audioPlayer:f}},CreateHomePage=function(){var g=document.createElement("Div"),h=document.createElement("Div");h.className="home";var f=document.createElement("Div");
f.className="head";var c=document.createElement("H1");c.appendChild(document.createTextNode("Welcome."));f.appendChild(c);c=document.createElement("Div");c.appendChild(document.createTextNode(data.intro));f.appendChild(c);h.appendChild(f);f=CreateBoxView([{id:"music",title:"Music",path:"/music",imgSrc:"/img/music/main.jpg"},{id:"soft",title:"Software",path:"/soft",imgSrc:"/img/soft/main.jpg"},{id:"resume",title:"Resumes",path:"/resume",imgSrc:"/img/resume/main.jpg"}],function(b){pages.gotoPage(b.id);
return!0});h.appendChild(f);f=[];for(c=0;c<data.sites.length;c++){var k=data.sites[c],j=document.createElement("Div"),m=document.createElement("Div"),n=document.createElement("A");n.appendChild(document.createTextNode(k.name));n.href=k.link;n.setAttribute("target","_blank");m.appendChild(n);j.appendChild(m);m=document.createElement("Div");m.appendChild(document.createTextNode(k.desc));j.appendChild(m);f.push({id:k.name,node:j})}f=CreateList("Awesome Sites",f);f.className+=" sites";h.appendChild(f);
f={id:"contactEmail",node:document.createElement("A")};f.node.appendChild(document.createTextNode(data.contact.email));f.node.href="mailto:"+data.contact.email;f=CreateList("Contact",[f]);f.className+=" contact";h.appendChild(f);g.appendChild(h);var i={node:g,subPages:[],changeSubPage:function(b,a,d){i.subPages=[];d||pages.pushState("home",i.subPages)}};return i},CreateMusicPage=function(){function g(a,b,d,c,f){(c=!1!==c)?transition.fade(a,b,function(a){a==transition.SUCCESS&&C.changePage(d[0],!c);
a==transition.STARTING&&(s.subPages=d,f||pages.pushState("music",s.subPages))}):(a.replaceChild(b,a.firstChild),C.changePage(d[0],!c),s.subPages=d,f||pages.pushState("music",s.subPages))}function h(a,b,d){g(equipmentContent,a.content,["equipment",a.type,a.title],b,d)}function f(a,b,d){g(y,a.content,["artists",a.title],b,d);return!0}function c(a,b,d){g(equipmentContent,a.content,["equipment",a.title],b,d);return!0}function k(a,b){g(y,w,["artists"],a,b)}function j(a,b){g(equipmentContent,z,["equipment"],
a,b)}for(var m=[],n=[],i=0;i<data.artists.length;i++){var b=data.artists[i],a=document.createElement("Div");a.className="artist";var d=document.createElement("Img");d.src="/img/music/"+b.name+"/main.jpg";d.alt="";a.appendChild(d);var p=document.createElement("Div");p.appendChild(document.createTextNode(b.description));a.appendChild(p);for(p=0;p<b.albums.length;p++){var l=b.albums[p],q=document.createElement("Div"),o=document.createElement("Img");o.addEventListener("error",function(a){a.target.parentNode.removeChild(a.target)},
!1);o.src="/img/music/"+b.name+"/"+l.name+".png";o.alt="";q.appendChild(o);o=document.createElement("Div");o.appendChild(document.createTextNode(l.description));q.appendChild(o);q=CreateSubSection(l.name,"",q);l.link&&(o=document.createElement("A"),o.appendChild(document.createTextNode(l.link)),o.href=l.link,o.setAttribute("target","_blank"),o.className="Content",q.appendChild(o));var t=document.createElement("Div");t.className="description";t.appendChild(document.createTextNode(" "));t.setAttribute("aria-live",
"polite");for(var v=function(a){return function(b){var d=document.createElement("Div"),c=document.createElement("Div");c.className="title";c.appendChild(document.createTextNode(b.text));b=b.desc.replace(/\n/g,"</div><div>");d.innerHTML="<div>"+b+"</div>";d.insertBefore(c,d.firstChild);a.replaceChild(d,a.firstChild);a.style.paddingLeft=a.previousSibling.offsetWidth+35+"px"}}(t),r=[],u=0;l.songs&&u<l.songs.length;u++){var A=l.songs[u],B=i+"/"+p+"/"+u,D=document.createElement("Div"),s={id:B,node:D,text:A.name,
desc:A.description,callback:v};A.recording&&(o=document.createElement("Div"),o.className="control play",o.setAttribute("role","button"),D.appendChild(o),A.callback=function(a,b,d){return function(c){a.className=c?"control pause":"control play";b(d)}}(o,v,s),B=function(a){return function(){pages.audioPlayer.toggle(a);return true}}(B),o.addEventListener("keydown",keyToClick(B),!1));o=document.createElement("Span");o.appendChild(document.createTextNode(A.name));D.appendChild(o);r.push(s)}o=function(a){pages.audioPlayer.toggle(a.id)};
l.songs&&0<l.songs.length&&(l=CreateList("Tracks",r,o),q.appendChild(l),q.appendChild(t));a.appendChild(q)}l=document.createElement("A");l.href="/music/artists";l.className="back";l.addEventListener("click",function(a){return preventDefaultLink(a)},!1);l.addEventListener("click",k,!1);l.addEventListener("keydown",keyToClick(k),!1);l.setAttribute("role","button");l.setAttribute("tabindex","0");l.setAttribute("title","Back");p=document.createElement("Div");p.appendChild(CreatePageTitle(b.name));p.appendChild(l);
p.appendChild(a);p={id:b.name,title:b.name,path:"/music/artists/"+b.name,imgSrc:d.src,content:p};b.end?n.push(p):m.push(p)}for(var x=[],i=0;i<data.equipment.length;i++){e=data.equipment[i];b=[];a={id:e.name,title:e.name,path:"/music/equipment/"+e.name,imgSrc:"/img/equipment/"+e.name+"/main.jpg"};for(p=0;p<e.equipment.length;p++)d=e.equipment[p],o=function(a){return function(){c(a)}}(a),l=document.createElement("A"),l.href="/music/equipment/"+e.name,l.className="back",l.addEventListener("click",function(a){return preventDefaultLink(a)},
!1),l.addEventListener("click",o,!1),l.addEventListener("keydown",keyToClick(o),!1),l.setAttribute("role","button"),l.setAttribute("tabindex","0"),l.setAttribute("title","Back"),o=document.createElement("Img"),o.src="/img/equipment/"+e.name+"/"+d.name+".jpg",q=document.createElement("Div"),q.appendChild(o),o=document.createElement("Div"),o.appendChild(CreatePageTitle(d.name)),o.appendChild(l),o.appendChild(q),b.push({id:d.name,title:d.name,path:"/music/equipment/"+e.name+"/"+d.name,imgSrc:"/img/equipment/"+
e.name+"/"+d.name+".jpg",content:o,type:e.name});l=document.createElement("A");l.href="/music/equipment";l.className="back";l.addEventListener("click",function(a){return preventDefaultLink(a)},!1);l.addEventListener("click",j,!1);l.addEventListener("keydown",keyToClick(j),!1);l.setAttribute("role","button");l.setAttribute("tabindex","0");l.setAttribute("title","Back");q=CreateBoxView(b,h);p=document.createElement("Div");p.className="equipmentSection";p.appendChild(CreatePageTitle(e.name));p.appendChild(l);
p.appendChild(q);a.content=p;a.tiles=b;x.push(a)}i=document.createElement("Div");i.className="artists";var y=document.createElement("Div");i.appendChild(y);var w=document.createElement("Div"),p=CreateSubSection("Current Acts","",CreateBoxView(m,f)),b=CreateSubSection("Previous Acts","",CreateBoxView(n,f));w.appendChild(CreatePageTitle("Related Acts"));w.appendChild(p);w.appendChild(b);y.appendChild(w);p=document.createElement("Div");p.className="equipment";equipmentContent=document.createElement("Div");
p.appendChild(equipmentContent);var z=document.createElement("Div"),b=CreateBoxView(x,c);z.appendChild(CreatePageTitle("Equipment"));z.appendChild(b);equipmentContent.appendChild(z);var C=CreateNavigation("Navigation",{artists:{title:"Related Acts",node:i},equipment:{title:"Equipment",node:p}},"/music/","artists",function(a,b){var d="artists"===a?y:equipmentContent;if(d.firstChild===("artists"===a?w:z))a!=b&&(s.subPages=[a],pages.pushState("music",s.subPages));else if(d=d.children[0],a==b)"artists"==
a?k():j();else{var c="artists"===a?m.concat(n):x,f;for(f in c)if(d==c[f].content){s.subPages=[a,c[f].title];pages.pushState("music",s.subPages);return}k()}}),E=["artists"];return s={node:C.node,subPages:E,changeSubPage:function(a,b,d){if(!a||1>a.length)a=b?E:s.subPages;if("artists"==a[0]){if(1<a.length){var u=m.concat(n);a[1]=unescape(a[1]);for(var g=0;g<u.length;g++)if(u[g].title===a[1]){f(u[g],b,d);return}}k(b,d)}else if("equipment"==a[0]){if(1<a.length){a[1]=unescape(a[1]);for(g=0;g<x.length;g++)if(u=
x[g],u.title===a[1]){if(a[2]){a[2]=unescape(a[2]);for(var i=0;i<u.tiles.length;i++){var l=u.tiles[i];if(l.title===a[2]){h(l,b,d);return}}}c(x[g],b,d);return}}j(b,d)}}}},CreateSoftPage=function(){var g=document.createElement("Div");g.className="softwareProjects";for(var h=[],f=0;f<data.softwareProjects.length;f++){var c=data.softwareProjects[f],c={id:c.name,title:c.name,path:"https://github.com/deadheadrussell/"+escape(c.repository_name),imgSrc:"/img/soft/"+c.name+".png"};h.push(c)}g.appendChild(CreateBoxView(h));
h=document.createElement("div");h.className="softwareProjects";for(f=0;f<data.schoolProjects.length;f++){var c=data.schoolProjects[f],k=document.createElement("span");k.appendChild(document.createTextNode(c.description));c=CreateSubSection(c.course,"",k);h.appendChild(c)}var j=document.createElement("div");j.className="softwareProjects";for(f=0;f<data.workProjects.length;f++)c=data.workProjects[f],k=document.createElement("span"),k.appendChild(document.createTextNode(c.description)),c=CreateSubSection(c.name,
c.company,k),j.appendChild(c);var m={projects:{title:"Personal Projects",node:g},school:{title:"School Projects",node:h},work:{title:"Work Projects",node:j}},n=CreateNavigation("Navigation",m,"/soft/","projects",function(a,d){a!=d&&(b.subPages=[a],pages.pushState("soft",b.subPages))}),i=["projects"],b={node:n.node,subPages:i,changeSubPage:function(a,d,c){if(!a||1>a.length)a=d?i:b.subPages;a.splice(1);a[0]in m||(n.changePage("projects",!d),a=["projects"]);n.changePage(a[0],!d);b.subPages=a;c||pages.pushState("soft",
b.subPages)}};return b},CreateResumesPage=function(){for(var g={},h=0;h<data.resumes.length;h++){var f=data.resumes[h],c=document.createElement("Div");c.className="resumeWrapper";var k=document.createElement("Div");k.className="resumeLink";var j=function(b){var a=document.createElement("A");a.href="/resumes/"+f.name+"/full."+b.toLowerCase();a.target="_blank";a.appendChild(document.createTextNode("Download "+b.toUpperCase()));return a};k.appendChild(j("html"));k.appendChild(j("pdf"));j=new XMLHttpRequest;
j.open("GET","/resumes/"+f.name+"/part.html",!0);j.addEventListener("readystatechange",function(b,a){return function(d){4===d.target.readyState&&200===d.target.status&&(console.log(d),b.innerHTML=d.target.responseText,b.insertBefore(a,b.firstChild))}}(c,k),!1);j.send();g[f.name]={title:f.name,node:c}}var m=data.resumes[0].name,n=CreateNavigation("Navigation",g,"/resume/",m,function(b,a){b!=a&&(i.subPages=[b],pages.pushState("resume",i.subPages))}),i={node:n.node,subPages:[],changeSubPage:function(b,
a,d){if(!b||1>b.length)b=a?defaultSubPages:i.subPages;b.splice(1);var c=!1,f;for(f in g)g.hasOwnProperty(f)&&f==b[0]&&(n.changePage(f,!a),c=!0);c||(n.changePage(m,!a),b=[m]);i.subPages=b;d||pages.pushState("resume",i.subPages)}};return i};var CreateBanner=function(g,h){var f=document.createElement("Div");f.className="Banner";var c=document.createElement("H1");c.appendChild(document.createTextNode(g));f.appendChild(c);c=document.createElement("H2");c.appendChild(document.createTextNode(h));f.appendChild(c);c=document.createElement("Div");c.className="PlusOne";c.innerHTML='<div class="g-plusone" data-href="http://ajrussell.ca"></div>';f.appendChild(c);return f},CreateHeader=function(g,h,f,c){function k(b){a.select(b.currentTarget.id);
return!0}var j=document.createElement("Div"),m="";j.className="Header";for(var n in g){var i=document.createElement("A");i.id=n;i.href="/"+n;i.addEventListener("click",function(a){preventDefaultLink(a);return!0},!1);i.addEventListener("click",k,!1);i.addEventListener("keydown",keyToClick(k),!1);i.className="NoStyle";var b=document.createElement("Div");b.appendChild(document.createTextNode(g[n].text));i.appendChild(b);j.appendChild(i)}var a={select:function(a,b,c){a!=m?h(a,function(f){if(f==transition.STARTING){g[a].page.changeSubPage(b,
a==m,c);m=a;for(f=0;f<j.children.length;f++){var h=j.children[f];a===h.id?(h.className="Selected",h.setAttribute("tabindex","-1")):(h.className="",h.removeAttribute("tabindex"))}}}):g[a].page.changeSubPage(b,a==m,c)},node:j};a.select(f,c,!0);return a},CreateNavigation=function(g,h,f,c,k){function j(a){a=a.currentTarget.id;k(a,p);l.changePage(a)}var m=document.createElement("Div");m.className="NavigationMain";var n=document.createElement("Div");n.className="NavigationTitle";var i=document.createElement("Div");
i.className="Title";i.appendChild(document.createTextNode(g));n.appendChild(i);for(var b in h)g=document.createElement("A"),g.className="Pages NoStyle ButtonLink",g.href=escape(f+b),g.id=b,g.addEventListener("click",j,!1),g.addEventListener("click",function(a){return preventDefaultLink(a)},!1),g.addEventListener("keydown",keyToClick(j),!1),g.appendChild(document.createTextNode(h[b].title)),i=document.createElement("Div"),i.className="Arrow",i.appendChild(document.createTextNode(">")),g.appendChild(i),
h[b].titleNode=g,i=document.createElement("Div"),i.appendChild(h[b].node),h[b].node=i,n.appendChild(g);var a=document.createElement("Div");a.className="NavigationContent";var d=h[c].node,p=c;a.appendChild(d);m.appendChild(n);m.appendChild(a);var l={node:m,changePage:function(b,c){var f=h[b].node;p=b;c?(a.replaceChild(f,d),d=f):transition.slide(a,f,function(a){a==transition.SUCCESS&&(d=f)})}};return l},CreatePageTitle=function(g){var h=document.createElement("Div");h.className="PageTitle";h.appendChild(document.createTextNode(g));
return h},CreateList=function(g,h,f){var c=document.createElement("Div");c.className="List";var k=document.createElement("Div");k.className="Title";k.appendChild(document.createTextNode(g));c.appendChild(k);for(g=0;g<h.length;g++){var j=h[g],k=document.createElement("Div");k.id=j.id;k.className="Item";j.node?k.appendChild(j.node):j.text&&k.appendChild(document.createTextNode(j.text));if(f){var m=function(c){return function(){f(c);return!0}}(j);k.setAttribute("tabindex","0");k.addEventListener("click",
m,!1);k.addEventListener("keydown",keyToClick(m),!1);j.callback&&(m=function(c){return function(){j.callback(c)}}(j),k.addEventListener("mouseover",m,!1),k.addEventListener("focus",m,!1))}c.appendChild(k)}return c},CreateSubSection=function(g,h,f){var c=document.createElement("Div");c.className="SubSection";var k=document.createElement("Div");k.className="Title";k.appendChild(document.createTextNode(g));c.appendChild(k);h instanceof HTMLElement?g=h:(g=document.createElement("Div"),g.appendChild(document.createTextNode(h)));
g.className="SubTitle";c.appendChild(g);h=document.createElement("Div");h.className="Content";h.appendChild(f);c.appendChild(h);return c};
function CreateBoxView(g,h){var f=document.createElement("Div");f.className="Boxes";for(var c=0;c<g.length;c++){var k=g[c],j=document.createElement("A");j.className="NoStyle";if(h){j.href=escape(k.path);var m=function(c){return function(){h(c);return!0}}(k);j.addEventListener("click",function(c){return preventDefaultLink(c)},!1);j.addEventListener("click",m,!1);j.addEventListener("keydown",keyToClick(m),!1)}else j.href=k.path,j.setAttribute("target","_blank");m=document.createElement("Img");m.src=
k.imgSrc;m.alt="";m.setAttribute("border","0");j.appendChild(m);m=document.createElement("Div");m.appendChild(document.createTextNode(k.title));j.appendChild(m);f.appendChild(j)}return f}
function CreateAudioPlayer(){var g,h,f,c;function k(a){var b=document.createElement("Audio");a&&(b.src=b.canPlayType("audio/ogg")?a+".ogg":a+".mp3",b.controls=!0,b.addEventListener("ended",n,!1),b.addEventListener("error",n,!1),b.addEventListener("playing",function(){i(!0)},!1),b.addEventListener("pause",function(){i(!1)},!1));return b}function j(){r.toggleDisplay();return!0}function m(a){"Next"==a.target.className?r.playNext():r.playPrev();"click"==a.type&&a.target.blur()}function n(a){if(o||"ended"==
a.type||"error"==a.type){"error"==a.type&&t++;if(5==t)return t=0,!1;r.playNext()}else r.playPrev();return!0}function i(a){g&&g.callback&&g.callback(a)}var b=document.createElement("Div");b.className="AudioPlayer Audio";b.style.display="none";var a=document.createElement("Div"),d=document.createElement("Div"),p=document.createElement("Span");d.appendChild(p);a.appendChild(d);var l=k();a.appendChild(l);d=document.createElement("Div");d.className="Prev";d.setAttribute("role","button");d.setAttribute("tabindex",
"0");a.appendChild(d);var q=document.createElement("Div");q.className="Next";q.setAttribute("role","button");q.setAttribute("tabindex","0");a.appendChild(q);c=f=h=g=void 0;var o=!0,t=0,v=!0,r={toggleDisplay:function(c){!c&&!1!==c&&(c=!v);if(c)transition.isUsingTransitions()?b.style[transition.getTransformStyle()]="translate(0px, 0px)":b.style.bottom="0px";else{var d=a.offsetHeight;transition.isUsingTransitions()?b.style[transition.getTransformStyle()]="translate(0px, "+d+"px)":b.style.bottom=-d+"px"}v=
c},play:function(d){if(d&&d!=c){i(!1);var j=d.split("/");h=data.artists[j[0]];f=h.albums[j[1]];g=f.songs[j[2]];c=d;p.innerHTML="";d=document.createElement("Div");d.appendChild(document.createTextNode(h.name));d.className="Artist";p.appendChild(d);d=document.createElement("Div");d.appendChild(document.createTextNode(f.name));d.className="Album";p.appendChild(d);d=document.createElement("Div");d.appendChild(document.createTextNode(g.name));d.className="Song";p.appendChild(d);d=h.name+"/"+f.name+"/"+
g.name;a.removeChild(l);l=k("/audio/"+escape(d));a.appendChild(l);l.play()}else if(l.paused)l.play();else return;b.style.display=""},playNext:function(){o=!0;var a=c.split("/"),b=data.artists[a[0]],d=b.albums[a[1]];for(a[2]++;a[2]>=d.songs.length||!d.songs[a[2]].recording;){for(a[1]++;a[1]>=b.albums.length;)a[0]=(a[0]+1)%data.artists.length,b=data.artists[a[0]],a[1]=0;d=b.albums[a[1]];a[2]=0}r.play(a.join("/"));return!0},playPrev:function(){o=!1;var a=c.split("/"),b=data.artists[a[0]],d=b.albums[a[1]];
for(a[2]--;0>a[2]||!d.songs[a[2]].recording;){for(a[1]--;0>a[1];)a[0]=(a[0]+data.artists.length-1)%data.artists.length,b=data.artists[a[0]],a[1]=b.albums.length-1;d=b.albums[a[1]];a[2]=d.songs.length-1}r.play(a.join("/"));return!0},pause:function(){l.pause()},toggle:function(a){r.isPlaying(a)?r.pause():r.play(a)},isPlaying:function(a){return a&&a!=c?!1:!l.paused},getNode:function(){return b}};d.addEventListener("click",m,!1);d.addEventListener("keydown",keyToClick(m),!1);d.setAttribute("title","Previous Track");
q.addEventListener("click",m,!1);q.addEventListener("keydown",keyToClick(m),!1);q.setAttribute("title","Next Track");d=document.createElement("Span");d.className="ButtonMain";d.appendChild(document.createTextNode("Audio Player"));d.setAttribute("role","button");d.setAttribute("tabindex","0");b.appendChild(d);b.appendChild(a);d.addEventListener("click",j,!1);d.addEventListener("keydown",keyToClick(j),!1);return r}
function preventDefaultLink(g){return window.history&&window.history.pushState?(g.preventDefault(),!1):!0}function keyToClick(g,h){h||(h=[13,32]);return function(f){if(0<=h.indexOf(f.keyCode))return f.stopPropagation(),f.preventDefault(),g(f)}};(function(){function g(b,a,d,f){function h(){a.removeEventListener(k,h,!1);b.removeChild(q);b.style.overflow="";b.style.height="";q.style[c]="";q.style.opacity="";q.style[j]="";a.style[c]="";a.style.opacity="";a.style[j]="";a.style.position="";a.style.top="";n=!1;f(window.transition.SUCCESS);i&&(setTimeout(function(a){return function(){g(a.node,a.newPage,a.options,a.callback)}}(i),1),i=null)}if(a===b||!b||!a||!window.history||!window.history.pushState)f(window.transition.FAILED);else if(n)i?f(window.transition.FAILED):
i={node:b,newPage:a,options:d,callback:f};else{var q=b.firstChild;if(q===a)f(window.transition.STARTING),f(window.transition.SUCCESS);else if(a.parentElement||document.body.compareDocumentPosition(b)&1)f(window.transition.FAILED);else if(n=!0,f(window.transition.STARTING),m){d=d||{};!d.fade&&!d.scale&&!d.slide&&(d.fade=!0);var o=d.duration||500,o=o+"ms",t=b.offsetWidth,v="";d.scale&&(v+=" scale(1.5)");d.slide&&(v+=" translateX(-"+t+"px)");a.style[j]=v;d.fade&&(a.style.opacity="0");a.style.position=
"absolute";a.style.top="0px";b.appendChild(a);q.style[c]=a.style[c]=""+o;if(d.slide||d.scale)b.style.overflow="hidden";setTimeout(function(){var c=Math.max(b.clientHeight,a.offsetHeight);b.style.height=c+"px";a.addEventListener(k,h,false);if(d.fade){q.style.opacity="0";a.style.opacity="1"}var f=c="";if(d.scale){c=c+" scale(0.5)";f=f+" scale(1)"}if(d.slide){c=c+(" translateX("+t+"px)");f=f+" translateX(0px)"}q.style[j]=c;a.style[j]=f},1)}else b.replaceChild(a,q),n=!1,f(window.transition.SUCCESS)}}
var h=document.createElement("Div"),f="webkitTransition"in h.style?"webkit":"MozTransition"in h.style?"Moz":"oTransition"in h.style?"o":"MSTransition"in h.style?"MS":"Transition"in h.style?"":"Old",h=void 0,c=f+"Transition",k=f+"TransitionEnd",j=f+"Transform";"Moz"==f&&(k="transitionend");var m=!0;"Old"==f&&(m=!1);window.transition={slide:function(b,a,d,c){return g(b,a,{slide:!0,duration:c},d)},scale:function(b,a,d,c){return g(b,a,{scale:!0,fade:!0,duration:c},d)},fade:function(b,a,d,c){return g(b,
a,{fade:!0,duration:c},d)},getTransitionEndEvent:function(){return k},getTransitionStyle:function(){return c},getTransformStyle:function(){return j},isUsingTransitions:function(){return m},STARTING:0,SUCCESS:1,FAILED:2};var n=!1,i=null})();
