var pages=null;
(function(){function b(){f&&(document.body.innerHTML='<div>Please use one of the following browsers<ul><li><a href="http://www.google.com/chrome/">Google Chrome</a></li><li><a href="http://www.mozilla.com">Mozilla Firefox</a></li></ul></div>')}var f=!1,c=!1,i=!1,j=function(){if(c&&f)try{var h=document.createElement("Div");document.body.appendChild(h);h.appendChild(CreateBanner(data.about.name,data.about.title));var l=location.pathname.split("/"),l=0==l[1].length?"home":l[1],j={home:{text:"Home",pageFunc:CreateHomePage},
music:{text:"Music",pageFunc:CreateMusicPage},soft:{text:"Software",pageFunc:CreateSoftPage},about:{text:"About",pageFunc:CreateAboutPage}},g;for(g in j)window.history&&window.history.pushState&&g!=l?window.setTimeout(function(m){return function(){j[m].page=j[m].pageFunc()}}(g),0):g==l&&(j[g].page=j[g].pageFunc());pages=CreatePageHandler(h,j,"home")}catch(a){console&&(console.log(a.message),console.log(a.stack)),i=!0,b()}};(function(){try{var f=new XMLHttpRequest;f.open("GET","/data.json",!0);f.addEventListener("readystatechange",
function(b){4===b.target.readyState&&200===b.target.status&&(data=JSON.parse(b.target.responseText),c=!0,j())},!1);f.send()}catch(l){i=!0,b()}})();window.addEventListener("load",function(){f=!0;i?b():j()},!1)})();var CreatePageHandler=function(b,f,c){function i(m,d,a){var b="/"+m;d&&0<d.length&&(b+="/"+d.join("/"));if(history[a])history[a]({id:m,subPages:d},escape(m),escape(b))}function j(a,d){i(a,d,"replaceState")}var h=location.pathname.split("/");h.shift();var l=h.shift();""!==l&&(c=l);var q=null,g=document.createElement("Div");g.className="Main";b.appendChild(g);var a=CreateHeader(f,function(a,d){var b=f[a].page;q?transition.fade(g,b.node,function(a){a==transition.SUCCESS&&(q=b);d&&d(a)}):(g.appendChild(b.node),
q=b,d(transition.STARTING),j(a,b.subPages))},c,h),c=CreateAudioPlayer();b.insertBefore(a.node,g);b.appendChild(c.getNode());window.addEventListener("popstate",function(b){(b=b.state)&&b.id&&a.select(b.id,b.subPages,!0);return!0},!1);return obj={gotoPage:function(b,d){a.select(b,d)},pushState:function(b,a){i(b,a,"pushState")},replaceState:j,audioPlayer:c}},CreateHomePage=function(){var b=document.createElement("Div"),f=document.createElement("Div");f.className="home";var c=document.createElement("Div");
c.className="head";var i=document.createElement("H1");i.appendChild(document.createTextNode("Welcome."));c.appendChild(i);i=document.createElement("Div");i.appendChild(document.createTextNode(data.intro));c.appendChild(i);f.appendChild(c);c=CreateBoxView([{id:"music",title:"Music",path:"/music",imgSrc:"/img/music/main.jpg"},{id:"soft",title:"Software",path:"/soft",imgSrc:"/img/soft/main.jpg"},{id:"about",title:"About",path:"/about",imgSrc:"/img/about/main.jpg"}],function(b){pages.gotoPage(b.id);return!0});
f.appendChild(c);c=[];for(i=0;i<data.sites.length;i++){var j=data.sites[i],h=document.createElement("Div"),l=document.createElement("Div"),q=document.createElement("A");q.appendChild(document.createTextNode(j.name));q.href=j.link;q.setAttribute("target","_blank");l.appendChild(q);h.appendChild(l);l=document.createElement("Div");l.appendChild(document.createTextNode(j.desc));h.appendChild(l);c.push({id:j.name,node:h})}c=CreateList("Awesome Sites",c);c.className+=" sites";f.appendChild(c);c={id:"contactEmail",
node:document.createElement("A")};c.node.appendChild(document.createTextNode(data.contact.email));c.node.href="mailto:"+data.contact.email;c=CreateList("Contact",[c]);c.className+=" contact";f.appendChild(c);b.appendChild(f);var g={node:b,subPages:[],changeSubPage:function(b,c,d){g.subPages=[];d||pages.pushState("home",g.subPages)}};return g},CreateMusicPage=function(){function b(b,a,d,c,s){(c=!1!==c)?transition.fade(b,a,function(b){b==transition.SUCCESS&&D.changePage(d[0],!c);b==transition.STARTING&&
(u.subPages=d,s||pages.pushState("music",u.subPages))}):(b.replaceChild(a,b.firstChild),D.changePage(d[0],!c),u.subPages=d,s||pages.pushState("music",u.subPages))}function f(a,d,c){b(equipmentContent,a.content,["equipment",a.type,a.title],d,c)}function c(a,d,c){b(z,a.content,["artists",a.title],d,c);return!0}function i(a,d,c){b(equipmentContent,a.content,["equipment",a.title],d,c);return!0}function j(a,d){b(z,x,["artists"],a,d)}function h(a,d){b(equipmentContent,A,["equipment"],a,d)}for(var l=[],
q=[],g=0;g<data.artists.length;g++){var a=data.artists[g],m=document.createElement("Div");m.className="artist";var d=document.createElement("Img");d.src="/img/music/"+a.name+"/main.jpg";d.alt="";m.appendChild(d);var o=document.createElement("Div");o.appendChild(document.createTextNode(a.description));m.appendChild(o);for(o=0;o<a.albums.length;o++){var k=a.albums[o],r=document.createElement("Div"),n=document.createElement("Img");n.addEventListener("error",function(a){a.target.parentNode.removeChild(a.target)},
!1);n.src="/img/music/"+a.name+"/"+k.name+".png";n.alt="";r.appendChild(n);n=document.createElement("Div");n.appendChild(document.createTextNode(k.description));r.appendChild(n);r=CreateSubSection(k.name,"",r);k.link&&(n=document.createElement("A"),n.appendChild(document.createTextNode(k.link)),n.href=k.link,n.setAttribute("target","_blank"),n.className="Content",r.appendChild(n));var v=document.createElement("Div");v.className="description";v.appendChild(document.createTextNode(" "));v.setAttribute("aria-live",
"polite");for(var w=function(a){return function(b){var d=document.createElement("Div"),c=document.createElement("Div");c.className="title";c.appendChild(document.createTextNode(b.text));b=b.desc.replace(/\n/g,"</div><div>");d.innerHTML="<div>"+b+"</div>";d.insertBefore(c,d.firstChild);a.replaceChild(d,a.firstChild);a.style.paddingLeft=a.previousSibling.offsetWidth+35+"px"}}(v),t=[],s=0;k.songs&&s<k.songs.length;s++){var B=k.songs[s],C=g+"/"+o+"/"+s,E=document.createElement("Div"),u={id:C,node:E,text:B.name,
desc:B.description,callback:w};B.recording&&(n=document.createElement("Div"),n.className="control play",n.setAttribute("role","button"),E.appendChild(n),B.callback=function(a,b,d){return function(c){a.className=c?"control pause":"control play";b(d)}}(n,w,u),C=function(a){return function(){pages.audioPlayer.toggle(a);return true}}(C),n.addEventListener("keydown",keyToClick(C),!1));n=document.createElement("Span");n.appendChild(document.createTextNode(B.name));E.appendChild(n);t.push(u)}n=function(a){pages.audioPlayer.toggle(a.id)};
k.songs&&0<k.songs.length&&(k=CreateList("Tracks",t,n),r.appendChild(k),r.appendChild(v));m.appendChild(r)}k=document.createElement("A");k.href="/music/artists";k.className="back";k.addEventListener("click",function(a){return preventDefaultLink(a)},!1);k.addEventListener("click",j,!1);k.addEventListener("keydown",keyToClick(j),!1);k.setAttribute("role","button");k.setAttribute("tabindex","0");k.setAttribute("title","Back");o=document.createElement("Div");o.appendChild(CreatePageTitle(a.name));o.appendChild(k);
o.appendChild(m);o={id:a.name,title:a.name,path:"/music/artists/"+a.name,imgSrc:d.src,content:o};a.end?q.push(o):l.push(o)}for(var y=[],g=0;g<data.equipment.length;g++){e=data.equipment[g];a=[];m={id:e.name,title:e.name,path:"/music/equipment/"+e.name,imgSrc:"/img/equipment/"+e.name+"/main.jpg"};for(o=0;o<e.equipment.length;o++)d=e.equipment[o],n=function(a){return function(){i(a)}}(m),k=document.createElement("A"),k.href="/music/equipment/"+e.name,k.className="back",k.addEventListener("click",function(a){return preventDefaultLink(a)},
!1),k.addEventListener("click",n,!1),k.addEventListener("keydown",keyToClick(n),!1),k.setAttribute("role","button"),k.setAttribute("tabindex","0"),k.setAttribute("title","Back"),n=document.createElement("Img"),n.src="/img/equipment/"+e.name+"/"+d.name+".jpg",r=document.createElement("Div"),r.appendChild(n),n=document.createElement("Div"),n.appendChild(CreatePageTitle(d.name)),n.appendChild(k),n.appendChild(r),a.push({id:d.name,title:d.name,path:"/music/equipment/"+e.name+"/"+d.name,imgSrc:"/img/equipment/"+
e.name+"/"+d.name+".jpg",content:n,type:e.name});k=document.createElement("A");k.href="/music/equipment";k.className="back";k.addEventListener("click",function(a){return preventDefaultLink(a)},!1);k.addEventListener("click",h,!1);k.addEventListener("keydown",keyToClick(h),!1);k.setAttribute("role","button");k.setAttribute("tabindex","0");k.setAttribute("title","Back");r=CreateBoxView(a,f);o=document.createElement("Div");o.className="equipmentSection";o.appendChild(CreatePageTitle(e.name));o.appendChild(k);
o.appendChild(r);m.content=o;m.tiles=a;y.push(m)}g=document.createElement("Div");g.className="artists";var z=document.createElement("Div");g.appendChild(z);var x=document.createElement("Div"),o=CreateSubSection("Current Acts","",CreateBoxView(l,c)),a=CreateSubSection("Previous Acts","",CreateBoxView(q,c));x.appendChild(CreatePageTitle("Related Acts"));x.appendChild(o);x.appendChild(a);z.appendChild(x);o=document.createElement("Div");o.className="equipment";equipmentContent=document.createElement("Div");
o.appendChild(equipmentContent);var A=document.createElement("Div"),a=CreateBoxView(y,i);A.appendChild(CreatePageTitle("Equipment"));A.appendChild(a);equipmentContent.appendChild(A);var D=CreateNavigation("Navigation",{artists:{title:"Related Acts",node:g},equipment:{title:"Equipment",node:o}},"/music/","artists",function(a,b){var d="artists"===a?z:equipmentContent;if(d.firstChild===("artists"===a?x:A))a!=b&&(u.subPages=[a],pages.pushState("music",u.subPages));else if(d=d.children[0],a==b)"artists"==
a?j():h();else{var c="artists"===a?l.concat(q):y,s;for(s in c)if(d==c[s].content){u.subPages=[a,c[s].title];pages.pushState("music",u.subPages);return}j()}}),F=["artists"];return u={node:D.node,subPages:F,changeSubPage:function(a,b,d){if(!a||1>a.length)a=b?F:u.subPages;if("artists"==a[0]){if(1<a.length){var s=l.concat(q);a[1]=unescape(a[1]);for(var m=0;m<s.length;m++)if(s[m].title===a[1]){c(s[m],b,d);return}}j(b,d)}else if("equipment"==a[0]){if(1<a.length){a[1]=unescape(a[1]);for(m=0;m<y.length;m++)if(s=
y[m],s.title===a[1]){if(a[2]){a[2]=unescape(a[2]);for(var g=0;g<s.tiles.length;g++){var k=s.tiles[g];if(k.title===a[2]){f(k,b,d);return}}}i(y[m],b,d);return}}h(b,d)}}}},CreateSoftPage=function(){var b=document.createElement("Div");b.className="resumeWrapper";if(0<data.resumes.length){var f=document.createElement("Div");f.className="resumeLink";var c=function(a){var b=document.createElement("A");b.href="/resumes/"+data.resumes[0].path+"."+a.toLowerCase();b.target="_blank";b.appendChild(document.createTextNode(a.toUpperCase()+
" Version"));return b};f.appendChild(c("html"));f.appendChild(c("pdf"));c=new XMLHttpRequest;c.open("GET","/resumes/"+data.resumes[0].path+"_part.html",!0);c.addEventListener("readystatechange",function(a){4===a.target.readyState&&200===a.target.status&&(b.innerHTML=a.target.responseText,b.insertBefore(f,b.firstChild))},!1);c.send()}c=document.createElement("Div");c.className="softwareProjects";for(var i=0;i<data.softwareProjects.length;i++){p=data.softwareProjects[i];var j=document.createElement("Div"),
h=document.createElement("A");h.href="/software/"+p.name+".zip";h.appendChild(document.createTextNode("Source"));j.appendChild(h);h=document.createElement("Img");h.src="/img/soft/"+p.name+".png";j.appendChild(h);h=document.createElement("P");h.appendChild(document.createTextNode(p.description));j.appendChild(h);c.appendChild(CreateSubSection(p.name,"",j))}var l=CreateNavigation("Navigation",{resume:{title:"Resume",node:b},projects:{title:"Projects",node:c}},"/soft/","resume",function(a,b){a!=b&&(g.subPages=
[a],pages.pushState("soft",g.subPages))}),q=["resume"],g={node:l.node,subPages:q,changeSubPage:function(a,b,d){if(!a||1>a.length)a=b?q:g.subPages;a.splice(1);"projects"==a[0]?l.changePage(a[0],!b):(l.changePage("resume",!b),a=["resume"]);g.subPages=a;d||pages.pushState("soft",g.subPages)}};return g},CreateAboutPage=function(){var b=document.createElement("Div");b.className="about";var f=document.createElement("Div");b.appendChild(f);f.appendChild(CreateSubSection("About","",document.createTextNode("Alright, alright already.  Maybe this page won't get done for while.  Writing about yourself is hard.")));
var c={node:b,subPages:[],changeSubPage:function(b,f,h){c.subPages=[];h||pages.pushState("about",c.subPages)}};return c};var CreateBanner=function(b,f){var c=document.createElement("Div");c.className="Banner";var i=document.createElement("H1");i.appendChild(document.createTextNode(b));c.appendChild(i);i=document.createElement("H2");i.appendChild(document.createTextNode(f));c.appendChild(i);i=document.createElement("Div");i.className="PlusOne";i.innerHTML='<div class="g-plusone" data-href="http://ajrussell.ca"></div>';c.appendChild(i);return c},CreateHeader=function(b,f,c,i){function j(a){m.select(a.currentTarget.id);
return!0}var h=document.createElement("Div"),l="";h.className="Header";for(var q in b){var g=document.createElement("A");g.id=q;g.href="/"+q;g.addEventListener("click",function(a){preventDefaultLink(a);return!0},!1);g.addEventListener("click",j,!1);g.addEventListener("keydown",keyToClick(j),!1);g.className="NoStyle";var a=document.createElement("Div");a.appendChild(document.createTextNode(b[q].text));g.appendChild(a);h.appendChild(g)}var m={select:function(a,c,m){a!=l?f(a,function(f){if(f==transition.STARTING){b[a].page.changeSubPage(c,
a==l,m);l=a;for(f=0;f<h.children.length;f++){var g=h.children[f];a===g.id?(g.className="Selected",g.setAttribute("tabindex","-1")):(g.className="",g.removeAttribute("tabindex"))}}}):b[a].page.changeSubPage(c,a==l,m)},node:h};m.select(c,i,!0);return m},CreateNavigation=function(b,f,c,i,j){function h(a){a=a.currentTarget.id;j(a,o);k.changePage(a)}var l=document.createElement("Div");l.className="NavigationMain";var q=document.createElement("Div");q.className="NavigationTitle";var g=document.createElement("Div");
g.className="Title";g.appendChild(document.createTextNode(b));q.appendChild(g);for(var a in f)b=document.createElement("A"),b.className="Pages NoStyle ButtonLink",b.href=escape(c+a),b.id=a,b.addEventListener("click",h,!1),b.addEventListener("click",function(a){return preventDefaultLink(a)},!1),b.addEventListener("keydown",keyToClick(h),!1),b.appendChild(document.createTextNode(f[a].title)),g=document.createElement("Div"),g.className="Arrow",g.appendChild(document.createTextNode(">")),b.appendChild(g),
f[a].titleNode=b,g=document.createElement("Div"),g.appendChild(f[a].node),f[a].node=g,q.appendChild(b);var m=document.createElement("Div");m.className="NavigationContent";var d=f[i].node,o=i;m.appendChild(d);l.appendChild(q);l.appendChild(m);var k={node:l,changePage:function(a,b){var c=f[a].node;o=a;b?(m.replaceChild(c,d),d=c):transition.slide(m,c,function(a){a==transition.SUCCESS&&(d=c)})}};return k},CreatePageTitle=function(b){var f=document.createElement("Div");f.className="PageTitle";f.appendChild(document.createTextNode(b));
return f},CreateList=function(b,f,c){var i=document.createElement("Div");i.className="List";var j=document.createElement("Div");j.className="Title";j.appendChild(document.createTextNode(b));i.appendChild(j);for(b=0;b<f.length;b++){var h=f[b],j=document.createElement("Div");j.id=h.id;j.className="Item";h.node?j.appendChild(h.node):h.text&&j.appendChild(document.createTextNode(h.text));if(c){var l=function(b){return function(){c(b);return!0}}(h);j.setAttribute("tabindex","0");j.addEventListener("click",
l,!1);j.addEventListener("keydown",keyToClick(l),!1);h.callback&&(l=function(b){return function(){h.callback(b)}}(h),j.addEventListener("mouseover",l,!1),j.addEventListener("focus",l,!1))}i.appendChild(j)}return i},CreateSubSection=function(b,f,c){var i=document.createElement("Div");i.className="SubSection";var j=document.createElement("Div");j.className="Title";j.appendChild(document.createTextNode(b));i.appendChild(j);f instanceof HTMLElement?b=f:(b=document.createElement("Div"),b.appendChild(document.createTextNode(f)));
b.className="SubTitle";i.appendChild(b);f=document.createElement("Div");f.className="Content";f.appendChild(c);i.appendChild(f);return i};
function CreateBoxView(b,f){var c=document.createElement("Div");c.className="Boxes";for(var i=0;i<b.length;i++){var j=b[i],h=document.createElement("A");h.href=escape(j.path);h.className="NoStyle";h.addEventListener("click",function(b){return preventDefaultLink(b)},!1);var l=function(b){return function(){f(b);return!0}}(j);h.addEventListener("click",l,!1);h.addEventListener("keydown",keyToClick(l),!1);l=document.createElement("Img");l.src=j.imgSrc;l.alt="";l.setAttribute("border","0");h.appendChild(l);
l=document.createElement("Div");l.appendChild(document.createTextNode(j.title));h.appendChild(l);c.appendChild(h)}return c}
function CreateAudioPlayer(){var b,f,c,i;function j(a){var b=document.createElement("Audio");a&&(b.src=b.canPlayType("audio/ogg")?a+".ogg":a+".mp3",b.controls=!0,b.addEventListener("ended",q,!1),b.addEventListener("error",q,!1),b.addEventListener("playing",function(){g(!0)},!1),b.addEventListener("pause",function(){g(!1)},!1));return b}function h(){t.toggleDisplay();return!0}function l(a){"Next"==a.target.className?t.playNext():t.playPrev();"click"==a.type&&a.target.blur()}function q(a){if(n||"ended"==
a.type||"error"==a.type){"error"==a.type&&v++;if(5==v)return v=0,!1;t.playNext()}else t.playPrev();return!0}function g(a){b&&b.callback&&b.callback(a)}var a=document.createElement("Div");a.className="AudioPlayer Audio";a.style.display="none";var m=document.createElement("Div"),d=document.createElement("Div"),o=document.createElement("Span");d.appendChild(o);m.appendChild(d);var k=j();m.appendChild(k);d=document.createElement("Div");d.className="Prev";d.setAttribute("role","button");d.setAttribute("tabindex",
"0");m.appendChild(d);var r=document.createElement("Div");r.className="Next";r.setAttribute("role","button");r.setAttribute("tabindex","0");m.appendChild(r);i=c=f=b=void 0;var n=!0,v=0,w=!0,t={toggleDisplay:function(b){!b&&!1!==b&&(b=!w);if(b)transition.isUsingTransitions()?a.style[transition.getTransformStyle()]="translate(0px, 0px)":a.style.bottom="0px";else{var c=m.offsetHeight;transition.isUsingTransitions()?a.style[transition.getTransformStyle()]="translate(0px, "+c+"px)":a.style.bottom=-c+"px"}w=
b},play:function(d){if(d&&d!=i){g(!1);var h=d.split("/");f=data.artists[h[0]];c=f.albums[h[1]];b=c.songs[h[2]];i=d;o.innerHTML="";d=document.createElement("Div");d.appendChild(document.createTextNode(f.name));d.className="Artist";o.appendChild(d);d=document.createElement("Div");d.appendChild(document.createTextNode(c.name));d.className="Album";o.appendChild(d);d=document.createElement("Div");d.appendChild(document.createTextNode(b.name));d.className="Song";o.appendChild(d);d=f.name+"/"+c.name+"/"+
b.name;m.removeChild(k);k=j("/audio/"+escape(d));m.appendChild(k);k.play()}else if(k.paused)k.play();else return;a.style.display=""},playNext:function(){n=!0;var a=i.split("/"),b=data.artists[a[0]],d=b.albums[a[1]];for(a[2]++;a[2]>=d.songs.length||!d.songs[a[2]].recording;){for(a[1]++;a[1]>=b.albums.length;)a[0]=(a[0]+1)%data.artists.length,b=data.artists[a[0]],a[1]=0;d=b.albums[a[1]];a[2]=0}t.play(a.join("/"));return!0},playPrev:function(){n=!1;var a=i.split("/"),b=data.artists[a[0]],d=b.albums[a[1]];
for(a[2]--;0>a[2]||!d.songs[a[2]].recording;){for(a[1]--;0>a[1];)a[0]=(a[0]+data.artists.length-1)%data.artists.length,b=data.artists[a[0]],a[1]=b.albums.length-1;d=b.albums[a[1]];a[2]=d.songs.length-1}t.play(a.join("/"));return!0},pause:function(){k.pause()},toggle:function(a){t.isPlaying(a)?t.pause():t.play(a)},isPlaying:function(a){return a&&a!=i?!1:!k.paused},getNode:function(){return a}};d.addEventListener("click",l,!1);d.addEventListener("keydown",keyToClick(l),!1);d.setAttribute("title","Previous Track");
r.addEventListener("click",l,!1);r.addEventListener("keydown",keyToClick(l),!1);r.setAttribute("title","Next Track");d=document.createElement("Span");d.className="ButtonMain";d.appendChild(document.createTextNode("Audio Player"));d.setAttribute("role","button");d.setAttribute("tabindex","0");a.appendChild(d);a.appendChild(m);d.addEventListener("click",h,!1);d.addEventListener("keydown",keyToClick(h),!1);return t}
function preventDefaultLink(b){return window.history&&window.history.pushState?(b.preventDefault(),!1):!0}function keyToClick(b,f){f||(f=[13,32]);return function(c){if(0<=f.indexOf(c.keyCode))return c.stopPropagation(),c.preventDefault(),b(c)}};(function(){function b(a,c,d,f){function k(){c.removeEventListener(j,k,!1);a.removeChild(r);a.style.overflow="";a.style.height="";r.style[i]="";r.style.opacity="";r.style[h]="";c.style[i]="";c.style.opacity="";c.style[h]="";c.style.position="";c.style.top="";q=!1;f(window.transition.SUCCESS);g&&(setTimeout(function(a){return function(){b(a.node,a.newPage,a.options,a.callback)}}(g),1),g=null)}if(c===a||!a||!c||!window.history||!window.history.pushState)f(window.transition.FAILED);else if(q)g?f(window.transition.FAILED):
g={node:a,newPage:c,options:d,callback:f};else{var r=a.firstChild;if(r===c)f(window.transition.STARTING),f(window.transition.SUCCESS);else if(c.parentElement||document.body.compareDocumentPosition(a)&1)f(window.transition.FAILED);else if(q=!0,f(window.transition.STARTING),l){d=d||{};!d.fade&&!d.scale&&!d.slide&&(d.fade=!0);var n=d.duration||500,n=n+"ms",v=a.offsetWidth,w="";d.scale&&(w+=" scale(1.5)");d.slide&&(w+=" translateX(-"+v+"px)");c.style[h]=w;d.fade&&(c.style.opacity="0");c.style.position=
"absolute";c.style.top="0px";a.appendChild(c);r.style[i]=c.style[i]=""+n;if(d.slide||d.scale)a.style.overflow="hidden";setTimeout(function(){var b=Math.max(a.clientHeight,c.offsetHeight);a.style.height=b+"px";c.addEventListener(j,k,false);if(d.fade){r.style.opacity="0";c.style.opacity="1"}var f=b="";if(d.scale){b=b+" scale(0.5)";f=f+" scale(1)"}if(d.slide){b=b+(" translateX("+v+"px)");f=f+" translateX(0px)"}r.style[h]=b;c.style[h]=f},1)}else a.replaceChild(c,r),q=!1,f(window.transition.SUCCESS)}}
var f=document.createElement("Div"),c="webkitTransition"in f.style?"webkit":"MozTransition"in f.style?"Moz":"oTransition"in f.style?"o":"MSTransition"in f.style?"MS":"Transition"in f.style?"":"Old",f=void 0,i=c+"Transition",j=c+"TransitionEnd",h=c+"Transform";"Moz"==c&&(j="transitionend");var l=!0;"Old"==c&&(l=!1);window.transition={slide:function(a,c,d,f){return b(a,c,{slide:!0,duration:f},d)},scale:function(a,c,d,f){return b(a,c,{scale:!0,fade:!0,duration:f},d)},fade:function(a,c,d,f){return b(a,
c,{fade:!0,duration:f},d)},getTransitionEndEvent:function(){return j},getTransitionStyle:function(){return i},getTransformStyle:function(){return h},isUsingTransitions:function(){return l},STARTING:0,SUCCESS:1,FAILED:2};var q=!1,g=null})();
