var pages=null;
(function(){function g(){f&&(document.body.innerHTML='<div>Please use one of the following browsers<ul><li><a href="http://www.google.com/chrome/">Google Chrome</a></li><li><a href="http://www.mozilla.com">Mozilla Firefox</a></li></ul></div>')}var f=!1,c=!1,b=!1,j=function(){if(c&&f)try{var k=document.createElement("Div");document.body.appendChild(k);k.appendChild(CreateBanner(data.about.name,data.about.title));var j=location.pathname.split("/"),j=0==j[1].length?"home":"soft"==j[1]?"software":j[1],
n={home:{text:"Home",pageFunc:CreateHomePage},music:{text:"Music",pageFunc:CreateMusicPage},software:{text:"Software",pageFunc:CreateSoftPage},resumes:{text:"Resumes / CVs",pageFunc:CreateResumesPage}},i;for(i in n)window.history&&window.history.pushState&&i!=j?window.setTimeout(function(a){return function(){n[a].page=n[a].pageFunc()}}(i),0):i==j&&(n[i].page=n[i].pageFunc());pages=CreatePageHandler(k,n,"home")}catch(d){console&&(console.log(d.message),console.log(d.stack)),b=!0,g()}};(function(){try{var f=
new XMLHttpRequest;f.open("GET","/data/",!0);f.addEventListener("readystatechange",function(b){4===b.target.readyState&&200===b.target.status&&(data=JSON.parse(b.target.responseText),c=!0,j())},!1);f.send()}catch(m){b=!0,g()}})();window.addEventListener("load",function(){f=!0;b?g():j()},!1)})();var CreatePageHandler=function(g,f,c){function b(a,h,d){var b="/"+a;h&&0<h.length&&(b+="/"+h.join("/"));if(history[d])history[d]({id:a,subPages:h},escape(a),escape(b))}function j(a,d){b(a,d,"replaceState")}var k=location.pathname.split("/");k.shift();var m=k.shift();"soft"==m?c="software":""!==m&&(c=m);var n=null,i=document.createElement("Div");i.className="Main";g.appendChild(i);var d=CreateHeader(f,function(a,d){var b=f[a].page;n?transition.fade(i,b.node,function(a){a==transition.SUCCESS&&(n=b);
d&&d(a)}):(i.appendChild(b.node),n=b,d(transition.STARTING),j(a,b.subPages))},c,k),c=CreateAudioPlayer();g.insertBefore(d.node,i);g.appendChild(c.getNode());window.addEventListener("popstate",function(a){(a=a.state)&&a.id&&d.select(a.id,a.subPages,!0);return!0},!1);return obj={gotoPage:function(a,b){d.select(a,b)},pushState:function(a,d){b(a,d,"pushState")},replaceState:j,audioPlayer:c}},CreateHomePage=function(){var g=document.createElement("Div"),f=document.createElement("Div");f.className="home";
var c=document.createElement("Div");c.className="head";var b=document.createElement("H1");b.appendChild(document.createTextNode("Welcome."));c.appendChild(b);b=document.createElement("Div");b.appendChild(document.createTextNode(data.intro));c.appendChild(b);f.appendChild(c);c=CreateBoxView([{id:"music",title:"Music",path:"/music",imgSrc:"/images/music.jpg"},{id:"software",title:"Software",path:"/software",imgSrc:"/images/software.jpg"},{id:"resumes",title:"Resumes",path:"/resumes",imgSrc:"/images/resumes.jpg"}],
function(d){pages.gotoPage(d.id);return!0});f.appendChild(c);c=[];for(b=0;b<data.sites.length;b++){var j=data.sites[b],k=document.createElement("Div"),m=document.createElement("Div"),n=document.createElement("A");n.appendChild(document.createTextNode(j.name));n.href=j.link;n.setAttribute("target","_blank");m.appendChild(n);k.appendChild(m);m=document.createElement("Div");m.appendChild(document.createTextNode(j.desc));k.appendChild(m);c.push({id:j.name,node:k})}c=CreateList("Awesome Sites",c);c.className+=
" sites";f.appendChild(c);c={id:"contactEmail",node:document.createElement("A")};c.node.appendChild(document.createTextNode(data.contact.email));c.node.href="mailto:"+data.contact.email;c=CreateList("Contact",[c]);c.className+=" contact";f.appendChild(c);g.appendChild(f);var i={node:g,subPages:[],changeSubPage:function(d,a,b){i.subPages=[];b||pages.pushState("home",i.subPages)}};return i},CreateMusicPage=function(){function g(a,d,b,h,c){(h=!1!==h)?transition.fade(a,d,function(a){a==transition.SUCCESS&&
C.changePage(b[0],!h);a==transition.STARTING&&(s.subPages=b,c||pages.pushState("music",s.subPages))}):(a.replaceChild(d,a.firstChild),C.changePage(b[0],!h),s.subPages=b,c||pages.pushState("music",s.subPages))}function f(a,d,b){g(equipmentContent,a.content,["equipment",a.type,a.title],d,b)}function c(a,d,b){g(z,a.content,["artists",a.title],d,b);return!0}function b(a,d,b){g(equipmentContent,a.content,["equipment",a.title],d,b);return!0}function j(a,d){g(z,w,["artists"],a,d)}function k(a,d){g(equipmentContent,
A,["equipment"],a,d)}for(var m=[],n=[],i=0;i<data.artists.length;i++){var d=data.artists[i],a=document.createElement("Div");a.className="artist";var h=document.createElement("Img");h.src="/data/images/artists/"+d.name+"/main.jpg";h.alt="";a.appendChild(h);var p=document.createElement("Div");p.appendChild(document.createTextNode(d.description));a.appendChild(p);for(p=0;p<d.albums.length;p++){var l=d.albums[p],q=document.createElement("Div"),o=document.createElement("Img");o.addEventListener("error",
function(a){a.target.parentNode.removeChild(a.target)},!1);o.src="/data/images/artists/"+d.name+"/"+l.name+".png";o.alt="";q.appendChild(o);o=document.createElement("Div");o.appendChild(document.createTextNode(l.description));q.appendChild(o);o=document.createElement("A");l.link?(o.appendChild(document.createTextNode(l.link)),o.href=l.link,o.setAttribute("target","_blank")):(o.appendChild(document.createTextNode("Download Album")),o.href="/data/audio/"+d.name+"/"+l.name+".zip");q=CreateSubSection(l.name,
"",q);q.appendChild(o);var t=document.createElement("Div");t.className="description";t.appendChild(document.createTextNode(" "));t.setAttribute("aria-live","polite");for(var v=function(a){return function(d){var b=document.createElement("Div"),h=document.createElement("Div");h.className="title";h.appendChild(document.createTextNode(d.text));var c=d.desc.replace(/\n/g,"</div><div>");b.innerHTML="<div>"+c+"</div>";b.insertBefore(h,b.firstChild);c=document.createElement("A");c.appendChild(document.createTextNode("Download Song"));
c.href=d.link;b.insertBefore(c,h);a.replaceChild(b,a.firstChild);a.style.paddingLeft=a.previousSibling.offsetWidth+35+"px"}}(t,d.name,l.name),r=[],u=0;l.songs&&u<l.songs.length;u++){var x=l.songs[u],B=i+"/"+p+"/"+u,D=document.createElement("Div"),s={id:B,node:D,text:x.name,desc:x.description,callback:v,link:"/data/audio/"+d.name+"/"+l.name+"/"+encodeURIComponent(x.name)+".mp3"};x.recording&&(o=document.createElement("Div"),o.className="control play",o.setAttribute("role","button"),D.appendChild(o),
x.callback=function(a,d,b){return function(h){a.className=h?"control pause":"control play";d(b)}}(o,v,s),B=function(a){return function(){pages.audioPlayer.toggle(a);return true}}(B),o.addEventListener("keydown",keyToClick(B),!1));o=document.createElement("Span");o.appendChild(document.createTextNode(x.name));D.appendChild(o);r.push(s)}o=function(a){pages.audioPlayer.toggle(a.id)};l.songs&&0<l.songs.length&&(l=CreateList("Tracks",r,o),q.appendChild(l),q.appendChild(t));a.appendChild(q)}l=document.createElement("A");
l.href="/music/artists";l.className="back";l.addEventListener("click",function(a){return preventDefaultLink(a)},!1);l.addEventListener("click",j,!1);l.addEventListener("keydown",keyToClick(j),!1);l.setAttribute("role","button");l.setAttribute("tabindex","0");l.setAttribute("title","Back");p=document.createElement("Div");p.appendChild(CreatePageTitle(d.name));p.appendChild(l);p.appendChild(a);p={id:d.name,title:d.name,path:"/music/artists/"+d.name,imgSrc:h.src,content:p};d.end?n.push(p):m.push(p)}for(var y=
[],i=0;i<data.equipment.length;i++){e=data.equipment[i];d=[];a={id:e.name,title:e.name,path:"/music/equipment/"+e.name,imgSrc:"/data/images/equipment/"+e.name+"/main.jpg"};for(p=0;p<e.equipment.length;p++)h=e.equipment[p],o=function(a){return function(){b(a)}}(a),l=document.createElement("A"),l.href="/music/equipment/"+e.name,l.className="back",l.addEventListener("click",function(a){return preventDefaultLink(a)},!1),l.addEventListener("click",o,!1),l.addEventListener("keydown",keyToClick(o),!1),l.setAttribute("role",
"button"),l.setAttribute("tabindex","0"),l.setAttribute("title","Back"),o=document.createElement("Img"),o.src="/data/images/equipment/"+e.name+"/"+h.name+".jpg",q=document.createElement("Div"),q.appendChild(o),o=document.createElement("Div"),o.appendChild(CreatePageTitle(h.name)),o.appendChild(l),o.appendChild(q),d.push({id:h.name,title:h.name,path:"/music/equipment/"+e.name+"/"+h.name,imgSrc:"/data/images/equipment/"+e.name+"/"+h.name+".jpg",content:o,type:e.name});l=document.createElement("A");
l.href="/music/equipment";l.className="back";l.addEventListener("click",function(a){return preventDefaultLink(a)},!1);l.addEventListener("click",k,!1);l.addEventListener("keydown",keyToClick(k),!1);l.setAttribute("role","button");l.setAttribute("tabindex","0");l.setAttribute("title","Back");q=CreateBoxView(d,f);p=document.createElement("Div");p.className="equipmentSection";p.appendChild(CreatePageTitle(e.name));p.appendChild(l);p.appendChild(q);a.content=p;a.tiles=d;y.push(a)}i=document.createElement("Div");
i.className="artists";var z=document.createElement("Div");i.appendChild(z);var w=document.createElement("Div"),p=CreateSubSection("Current Acts","",CreateBoxView(m,c)),d=CreateSubSection("Previous Acts","",CreateBoxView(n,c));w.appendChild(CreatePageTitle("Related Acts"));w.appendChild(p);w.appendChild(d);z.appendChild(w);p=document.createElement("Div");p.className="equipment";equipmentContent=document.createElement("Div");p.appendChild(equipmentContent);var A=document.createElement("Div"),d=CreateBoxView(y,
b);A.appendChild(CreatePageTitle("Equipment"));A.appendChild(d);equipmentContent.appendChild(A);var C=CreateNavigation("Navigation",{artists:{title:"Related Acts",node:i},equipment:{title:"Equipment",node:p}},"/music/","artists",function(a,d){var b="artists"===a?z:equipmentContent;if(b.firstChild===("artists"===a?w:A))a!=d&&(s.subPages=[a],pages.pushState("music",s.subPages));else if(b=b.children[0],a==d)"artists"==a?j():k();else{var h="artists"===a?m.concat(n):y,c;for(c in h)if(b==h[c].content){s.subPages=
[a,h[c].title];pages.pushState("music",s.subPages);return}j()}}),E=["artists"];return s={node:C.node,subPages:E,changeSubPage:function(a,d,h){if(!a||1>a.length)a=d?E:s.subPages;if("artists"==a[0]){if(1<a.length){var u=m.concat(n);a[1]=unescape(a[1]);for(var g=0;g<u.length;g++)if(u[g].title===a[1]){c(u[g],d,h);return}}j(d,h)}else if("equipment"==a[0]){if(1<a.length){a[1]=unescape(a[1]);for(g=0;g<y.length;g++)if(u=y[g],u.title===a[1]){if(a[2]){a[2]=unescape(a[2]);for(var l=0;l<u.tiles.length;l++){var i=
u.tiles[l];if(i.title===a[2]){f(i,d,h);return}}}b(y[g],d,h);return}}k(d,h)}}}},CreateSoftPage=function(){var g=document.createElement("Div");g.className="softwareProjects";for(var f=[],c=0;c<data.softwareProjects.length;c++){var b=data.softwareProjects[c],b={id:b.name,title:b.name,path:"https://github.com/deadheadrussell/"+escape(b.repository_name),imgSrc:"/data/images/personalProjects/"+b.name+".png"};f.push(b)}g.appendChild(CreateBoxView(f));f=document.createElement("div");f.className="softwareProjects";
for(c=0;c<data.schoolProjects.length;c++){var b=data.schoolProjects[c],j=document.createElement("span");j.appendChild(document.createTextNode(b.description));b=CreateSubSection(b.course,"",j);f.appendChild(b)}var k=document.createElement("div");k.className="softwareProjects";for(c=0;c<data.workProjects.length;c++)b=data.workProjects[c],j=document.createElement("span"),j.appendChild(document.createTextNode(b.description)),b=CreateSubSection(b.name,b.company,j),k.appendChild(b);var m={projects:{title:"Personal Projects",
node:g},school:{title:"School Projects",node:f},work:{title:"Work Projects",node:k}},n=CreateNavigation("Navigation",m,"/software/","projects",function(a,b){a!=b&&(d.subPages=[a],pages.pushState("software",d.subPages))}),i=["projects"],d={node:n.node,subPages:i,changeSubPage:function(a,b,c){if(!a||1>a.length)a=b?i:d.subPages;a.splice(1);a[0]in m||(n.changePage("projects",!b),a=["projects"]);n.changePage(a[0],!b);d.subPages=a;c||pages.pushState("software",d.subPages)}};return d},CreateResumesPage=
function(){for(var g={},f=0;f<data.resumes.length;f++){var c=data.resumes[f],b=document.createElement("Div");b.className="resumeWrapper";var j=document.createElement("Div");j.className="resumeLink";var k=function(d){var a=document.createElement("A");a.href="/data/resumes/"+c.name+"/full."+d.toLowerCase();a.target="_blank";a.appendChild(document.createTextNode("Download "+d.toUpperCase()));return a};j.appendChild(k("html"));j.appendChild(k("pdf"));k=new XMLHttpRequest;k.open("GET","/data/resumes/"+
c.name+"/part.html",!0);k.addEventListener("readystatechange",function(d,a){return function(b){4===b.target.readyState&&200===b.target.status&&(console.log(b),d.innerHTML=b.target.responseText,d.insertBefore(a,d.firstChild))}}(b,j),!1);k.send();g[c.name]={title:c.name,node:b}}var m=data.resumes[0].name,n=CreateNavigation("Navigation",g,"/resumes/",m,function(b,a){b!=a&&(i.subPages=[b],pages.pushState("resumes",i.subPages))}),i={node:n.node,subPages:[],changeSubPage:function(b,a,c){if(!b||1>b.length)b=
a?defaultSubPages:i.subPages;b.splice(1);var f=!1,l;for(l in g)g.hasOwnProperty(l)&&l==b[0]&&(n.changePage(l,!a),f=!0);f||(n.changePage(m,!a),b=[m]);i.subPages=b;c||pages.pushState("resumes",i.subPages)}};return i};var CreateBanner=function(g,f){var c=document.createElement("Div");c.className="Banner";var b=document.createElement("H1");b.appendChild(document.createTextNode(g));c.appendChild(b);b=document.createElement("H2");b.appendChild(document.createTextNode(f));c.appendChild(b);b=document.createElement("Div");b.className="PlusOne";b.innerHTML='<div class="g-plusone" data-href="http://ajrussell.ca"></div>';c.appendChild(b);return c},CreateHeader=function(g,f,c,b){function j(b){a.select(b.currentTarget.id);
return!0}var k=document.createElement("Div"),m="";k.className="Header";for(var n in g){var i=document.createElement("A");i.id=n;i.href="/"+n;i.addEventListener("click",function(a){preventDefaultLink(a);return!0},!1);i.addEventListener("click",j,!1);i.addEventListener("keydown",keyToClick(j),!1);i.className="NoStyle";var d=document.createElement("Div");d.appendChild(document.createTextNode(g[n].text));i.appendChild(d);k.appendChild(i)}var a={select:function(a,b,d){a!=m?f(a,function(c){if(c==transition.STARTING){g[a].page.changeSubPage(b,
a==m,d);m=a;for(c=0;c<k.children.length;c++){var f=k.children[c];a===f.id?(f.className="Selected",f.setAttribute("tabindex","-1")):(f.className="",f.removeAttribute("tabindex"))}}}):g[a].page.changeSubPage(b,a==m,d)},node:k};a.select(c,b,!0);return a},CreateNavigation=function(g,f,c,b,j){function k(a){a=a.currentTarget.id;j(a,p);l.changePage(a)}var m=document.createElement("Div");m.className="NavigationMain";var n=document.createElement("Div");n.className="NavigationTitle";var i=document.createElement("Div");
i.className="Title";i.appendChild(document.createTextNode(g));n.appendChild(i);for(var d in f)g=document.createElement("A"),g.className="Pages NoStyle ButtonLink",g.href=escape(c+d),g.id=d,g.addEventListener("click",k,!1),g.addEventListener("click",function(a){return preventDefaultLink(a)},!1),g.addEventListener("keydown",keyToClick(k),!1),g.appendChild(document.createTextNode(f[d].title)),i=document.createElement("Div"),i.className="Arrow",i.appendChild(document.createTextNode(">")),g.appendChild(i),
f[d].titleNode=g,i=document.createElement("Div"),i.appendChild(f[d].node),f[d].node=i,n.appendChild(g);var a=document.createElement("Div");a.className="NavigationContent";var h=f[b].node,p=b;a.appendChild(h);m.appendChild(n);m.appendChild(a);var l={node:m,changePage:function(b,d){var c=f[b].node;p=b;d?(a.replaceChild(c,h),h=c):transition.slide(a,c,function(a){a==transition.SUCCESS&&(h=c)})}};return l},CreatePageTitle=function(g){var f=document.createElement("Div");f.className="PageTitle";f.appendChild(document.createTextNode(g));
return f},CreateList=function(g,f,c){var b=document.createElement("Div");b.className="List";var j=document.createElement("Div");j.className="Title";j.appendChild(document.createTextNode(g));b.appendChild(j);for(g=0;g<f.length;g++){var k=f[g],j=document.createElement("Div");j.id=k.id;j.className="Item";k.node?j.appendChild(k.node):k.text&&j.appendChild(document.createTextNode(k.text));if(c){var m=function(b){return function(){c(b);return!0}}(k);j.setAttribute("tabindex","0");j.addEventListener("click",
m,!1);j.addEventListener("keydown",keyToClick(m),!1);k.callback&&(m=function(b){return function(){k.callback(b)}}(k),j.addEventListener("mouseover",m,!1),j.addEventListener("focus",m,!1))}b.appendChild(j)}return b},CreateSubSection=function(g,f,c){var b=document.createElement("Div");b.className="SubSection";var j=document.createElement("Div");j.className="Title";j.appendChild(document.createTextNode(g));b.appendChild(j);f instanceof HTMLElement?g=f:(g=document.createElement("Div"),g.appendChild(document.createTextNode(f)));
g.className="SubTitle";b.appendChild(g);f=document.createElement("Div");f.className="Content";f.appendChild(c);b.appendChild(f);return b};
function CreateBoxView(g,f){var c=document.createElement("Div");c.className="Boxes";for(var b=0;b<g.length;b++){var j=g[b],k=document.createElement("A");k.className="NoStyle";if(f){k.href=escape(j.path);var m=function(b){return function(){f(b);return!0}}(j);k.addEventListener("click",function(b){return preventDefaultLink(b)},!1);k.addEventListener("click",m,!1);k.addEventListener("keydown",keyToClick(m),!1)}else k.href=j.path,k.setAttribute("target","_blank");m=document.createElement("Img");m.src=
j.imgSrc;m.alt="";m.setAttribute("border","0");k.appendChild(m);m=document.createElement("Div");m.appendChild(document.createTextNode(j.title));k.appendChild(m);c.appendChild(k)}return c}
function CreateAudioPlayer(){var g,f,c,b;function j(a){var b=document.createElement("Audio");a&&(b.src=b.canPlayType("audio/ogg")?a+".ogg":a+".mp3",b.controls=!0,b.addEventListener("ended",n,!1),b.addEventListener("error",n,!1),b.addEventListener("playing",function(){i(!0)},!1),b.addEventListener("pause",function(){i(!1)},!1));return b}function k(){r.toggleDisplay();return!0}function m(a){"Next"==a.target.className?r.playNext():r.playPrev();"click"==a.type&&a.target.blur()}function n(a){if(o||"ended"==
a.type||"error"==a.type){"error"==a.type&&t++;if(5==t)return t=0,!1;r.playNext()}else r.playPrev();return!0}function i(a){g&&g.callback&&g.callback(a)}var d=document.createElement("Div");d.className="AudioPlayer Audio";d.style.display="none";var a=document.createElement("Div"),h=document.createElement("Div"),p=document.createElement("Span");h.appendChild(p);a.appendChild(h);var l=j();a.appendChild(l);h=document.createElement("Div");h.className="Prev";h.setAttribute("role","button");h.setAttribute("tabindex",
"0");a.appendChild(h);var q=document.createElement("Div");q.className="Next";q.setAttribute("role","button");q.setAttribute("tabindex","0");a.appendChild(q);b=c=f=g=void 0;var o=!0,t=0,v=!0,r={toggleDisplay:function(b){!b&&!1!==b&&(b=!v);if(b)transition.isUsingTransitions()?d.style[transition.getTransformStyle()]="translate(0px, 0px)":d.style.bottom="0px";else{var c=a.offsetHeight;transition.isUsingTransitions()?d.style[transition.getTransformStyle()]="translate(0px, "+c+"px)":d.style.bottom=-c+"px"}v=
b},play:function(h){if(h&&h!=b){i(!1);var k=h.split("/");f=data.artists[k[0]];c=f.albums[k[1]];g=c.songs[k[2]];b=h;p.innerHTML="";h=document.createElement("Div");h.appendChild(document.createTextNode(f.name));h.className="Artist";p.appendChild(h);h=document.createElement("Div");h.appendChild(document.createTextNode(c.name));h.className="Album";p.appendChild(h);h=document.createElement("Div");h.appendChild(document.createTextNode(g.name));h.className="Song";p.appendChild(h);h=f.name+"/"+c.name+"/"+
g.name;a.removeChild(l);l=j("/data/audio/"+escape(h));a.appendChild(l);l.play()}else if(l.paused)l.play();else return;d.style.display=""},playNext:function(){o=!0;var a=b.split("/"),d=data.artists[a[0]],c=d.albums[a[1]];for(a[2]++;a[2]>=c.songs.length||!c.songs[a[2]].recording;){for(a[1]++;a[1]>=d.albums.length;)a[0]=(a[0]+1)%data.artists.length,d=data.artists[a[0]],a[1]=0;c=d.albums[a[1]];a[2]=0}r.play(a.join("/"));return!0},playPrev:function(){o=!1;var a=b.split("/"),d=data.artists[a[0]],c=d.albums[a[1]];
for(a[2]--;0>a[2]||!c.songs[a[2]].recording;){for(a[1]--;0>a[1];)a[0]=(a[0]+data.artists.length-1)%data.artists.length,d=data.artists[a[0]],a[1]=d.albums.length-1;c=d.albums[a[1]];a[2]=c.songs.length-1}r.play(a.join("/"));return!0},pause:function(){l.pause()},toggle:function(a){r.isPlaying(a)?r.pause():r.play(a)},isPlaying:function(a){return a&&a!=b?!1:!l.paused},getNode:function(){return d}};h.addEventListener("click",m,!1);h.addEventListener("keydown",keyToClick(m),!1);h.setAttribute("title","Previous Track");
q.addEventListener("click",m,!1);q.addEventListener("keydown",keyToClick(m),!1);q.setAttribute("title","Next Track");h=document.createElement("Span");h.className="ButtonMain";h.appendChild(document.createTextNode("Audio Player"));h.setAttribute("role","button");h.setAttribute("tabindex","0");d.appendChild(h);d.appendChild(a);h.addEventListener("click",k,!1);h.addEventListener("keydown",keyToClick(k),!1);return r}
function preventDefaultLink(g){return window.history&&window.history.pushState?(g.preventDefault(),!1):!0}function keyToClick(g,f){f||(f=[13,32]);return function(c){if(0<=f.indexOf(c.keyCode))return c.stopPropagation(),c.preventDefault(),g(c)}};(function(){function g(d,a,c,f){function l(){a.removeEventListener(j,l,!1);d.removeChild(q);d.style.overflow="";d.style.height="";q.style[b]="";q.style.opacity="";q.style[k]="";a.style[b]="";a.style.opacity="";a.style[k]="";a.style.position="";a.style.top="";n=!1;f(window.transition.SUCCESS);i&&(setTimeout(function(a){return function(){g(a.node,a.newPage,a.options,a.callback)}}(i),1),i=null)}if(a===d||!d||!a||!window.history||!window.history.pushState)f(window.transition.FAILED);else if(n)i?f(window.transition.FAILED):
i={node:d,newPage:a,options:c,callback:f};else{var q=d.firstChild;if(q===a)f(window.transition.STARTING),f(window.transition.SUCCESS);else if(a.parentElement||document.body.compareDocumentPosition(d)&1)f(window.transition.FAILED);else if(n=!0,f(window.transition.STARTING),m){c=c||{};!c.fade&&!c.scale&&!c.slide&&(c.fade=!0);var o=c.duration||500,o=o+"ms",t=d.offsetWidth,v="";c.scale&&(v+=" scale(1.5)");c.slide&&(v+=" translateX(-"+t+"px)");a.style[k]=v;c.fade&&(a.style.opacity="0");a.style.position=
"absolute";a.style.top="0px";d.appendChild(a);q.style[b]=a.style[b]=""+o;if(c.slide||c.scale)d.style.overflow="hidden";setTimeout(function(){var b=Math.max(d.clientHeight,a.offsetHeight);d.style.height=b+"px";a.addEventListener(j,l,false);if(c.fade){q.style.opacity="0";a.style.opacity="1"}var f=b="";if(c.scale){b=b+" scale(0.5)";f=f+" scale(1)"}if(c.slide){b=b+(" translateX("+t+"px)");f=f+" translateX(0px)"}q.style[k]=b;a.style[k]=f},1)}else d.replaceChild(a,q),n=!1,f(window.transition.SUCCESS)}}
var f=document.createElement("Div"),c="webkitTransition"in f.style?"webkit":"MozTransition"in f.style?"Moz":"oTransition"in f.style?"o":"MSTransition"in f.style?"MS":"Transition"in f.style?"":"Old",f=void 0,b=c+"Transition",j=c+"TransitionEnd",k=c+"Transform";"Moz"==c&&(j="transitionend");var m=!0;"Old"==c&&(m=!1);window.transition={slide:function(b,a,c,f){return g(b,a,{slide:!0,duration:f},c)},scale:function(b,a,c,f){return g(b,a,{scale:!0,fade:!0,duration:f},c)},fade:function(b,a,c,f){return g(b,
a,{fade:!0,duration:f},c)},getTransitionEndEvent:function(){return j},getTransitionStyle:function(){return b},getTransformStyle:function(){return k},isUsingTransitions:function(){return m},STARTING:0,SUCCESS:1,FAILED:2};var n=!1,i=null})();
